### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Teraflopst** [RobertYim/ShadowsocksX#1]
最近更新 gfwlist 出现 404 问题，我想修复 ShadowsocksX 的 GFWlist URL，发现你已经修复了，我下载源代码后编译失败，请问你可以发给我一个已修复的 ShadowsocksX 的 `dmg` 文件吗？谢谢。

**Comment by RobertYim** [comment]
@onestark https://github.com/RobertYan/ShadowsocksX/releases/download/2.6.4/ShadowsocksX.2.6.4.zip

**Comment by Teraflopst** [comment]
@RobertYan 谢谢，已解决。

**Comment by ChengLuffy** [comment]
@onestark 怎么解决不能打开的问题的呢？

**Comment by Teraflopst** [comment]
@ChengLuffy https://github.com/shadowsocks/shadowsocks-iOS/issues/216
