### ISSUE TITLE
能不能加入Apple Script支持？

### ISSUE THREAD

**Issue by ghost** [RobertYim/ShadowsocksX#12]
平时开关挺频繁的，可不可以加入Apple Script支持，这样就可以用Alfred控制了

**Comment by Teraflopst** [comment]
@clavichord93 我写了一个Alfred Workflow，利用 AppleScript 模拟点击系统 Menubar，快速执行 ShadowsocksX 各个设置菜单项。可以在我的 [Alfred Workflows](https://github.com/onestark/alfred-workflows) 里下载。

![](https://raw.githubusercontent.com/onestark/alfred-workflows/master/assets/ssx-menu_shot.png)

**Comment by ghost** [comment]
@onestark 谢谢！真是太好了！另外能不能加入白名单功能？

**Comment by ghost** [comment]
@onestark 试了一下那个Workflow好像不管用诶。。。

**Comment by Teraflopst** [comment]
@clavichord93 我用 Alfred 3。具体是哪个功能不能用？

**Comment by RobertYim** [comment]
@onestark Thanks for the workflow.

@clavichord93 Besides, if you switch on and off frequently, try to use a browser plugin such as Proxy SwitchyOmega.
