### ISSUE TITLE
当ss长期不用时，需要重启ss才能正常使用

### ISSUE THREAD

**Issue by shenyunhuan** [RobertYim/ShadowsocksX#15]
如题

**Comment by shenyunhuan** [comment]
不能重现吗？忍住半天不去需要翻墙的网站，自动代理模式，麻烦再试下,可能作者你用ide或其它软件自动连接了谷歌之类的

**Comment by RobertYan** [comment]
I've testing this for about 5 hours and everything works just fine. Did you turn it off by clicking the menu, or there's another software has changed your network setting?

**Comment by RobertYim** [comment]
@shenyunhuan 
I've testing this for about 5 hours and everything works just fine. Did you turn it off by clicking the menu, or there's another software has changed your network settings?
