### ISSUE TITLE
您好，感谢您修复了gfwlist的ssX，但是新版ssx无法使用扫描二维码的功能

### ISSUE THREAD

**Issue by Chandler-Lu** [RobertYim/ShadowsocksX#2]
您好，感谢您修复了gfwlist的ssX，但是新版ssx无法使用扫描二维码的功能，我这里扫描二维码的功能是灰色的，不知道为什么。谢谢

**Comment by RobertYim** [comment]
@ltr970503 This feature(method) didn't implement yet, I'll find some time to fix it.

**Comment by RobertYim** [comment]
#4 fixed
