### ISSUE TITLE
10.9.5 不能使用？

### ISSUE THREAD

**Issue by mactrash** [RobertYim/ShadowsocksX#3]
希望可以解決這問題，謝謝

**Comment by RobertYan** [comment]
Try to build it on your own, simply change the Deployment Target to 10.9 .

**Comment by RobertYim** [comment]
@mactrash Try to build it on your own, simply change the Deployment Target to 10.9 .

**Comment by mactrash** [comment]
Can you help to build it, I just a layman and have no development platform, many thanks.
