### ISSUE TITLE
切换服务器自动不自动重连

### ISSUE THREAD

**Issue by algobun** [RobertYim/ShadowsocksX#6]
我有多个服务器，切换服务器后，连接还停留在原来的服务器上，需要退出再启动才能完成切换。

**Comment by RobertYim** [comment]
@bitweng I can't reproduce your issue on my machine. But I've just recompiled the app, you're welcome to try it out.

**Comment by algobun** [comment]
我举个例子，我有A和B两个服务器，当前用的是A，现在我切换到B。但是shadowsocks的连接并不会使用B，而是仍然使用A。我只有退出，再启动shadowsocks才会使用B。
